version: '3'
services:
    api-nginx:
        build:
            context: ./api/docker/development
            dockerfile: nginx.docker
        volumes:
            - ./api:/app
        depends_on:
            - api-php-fpm
        ports:
            - "8080:80"
    api-php-fpm:
        build:
            context: ./api/docker/development
            dockerfile: php-fpm.docker
        volumes:
            - ./api:/app
        depends_on:
            - api-postgres
            - api-redis
            - api-queue-redis
            - mailer
    api-php-cli:
        build:
            context: ./api/docker/development
            dockerfile: php-cli.docker
        volumes:
            - ./api:/app
            - ./docker/cache/composer:/root/.composer/cache
        depends_on:
            - api-postgres
            - api-redis
            - api-queue-redis
            - mailer
    api-postgres:
        image: postgres:13.1-alpine
        environment:
            POSTGRES_USER: app
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: app
        volumes:
            - ./docker/storage/pgsql:/var/lib/postgresql/data
        ports:
            - "54321:5432"
    api-redis:
        image: redis:5.0-alpine
        volumes:
            - ./docker/storage/redis:/data
        command:
            - 'redis-server'
            - '--databases 2'
            - '--save 900 1'
            - '--save 300 10'
            - '--save 60 10000'
            - '--requirepass secret'
    api-queue-redis:
        image: redis:5.0-alpine
        volumes:
            - ./docker/storage/queue_redis:/data
    mailer:
        image: mailhog/mailhog
        ports:
            - "8082:8025"